#!/bin/bash
for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec1${i}.txt -d data1${i}.txt --NP 10 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup1${i}.txt
done

echo "test 1 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec2${i}.txt -d data2${i}.txt --NP 20 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup2${i}.txt
done

echo "test 2 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec3${i}.txt -d data3${i}.txt --NP 50 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup3${i}.txt
done

echo "test 3 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec4${i}.txt -d data4${i}.txt --NP 100 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup4${i}.txt
done

echo "test 4 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec5${i}.txt -d data5${i}.txt --NP 200 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup5${i}.txt
done

echo "test 5 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec6${i}.txt -d data6${i}.txt --NP 500 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup6${i}.txt
done

echo "test 6 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec7${i}.txt -d data7${i}.txt --NP 1000 --F 0.7 --CR 0.8 --generations 100 --neurons 10 --quiet 1 >> vystup7${i}.txt
done

echo "test 7 done."

