#!/bin/bash
for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec1${i}.txt -d data1${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 100 --neurons 5 --quiet 1 >> vystup1${i}.txt
done
echo "test 1 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec2${i}.txt -d data2${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 200 --neurons 5 --quiet 1 >> vystup2${i}.txt
done
echo "test 2 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec3${i}.txt -d data3${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 300 --neurons 5 --quiet 1 >> vystup3${i}.txt
done
echo "test 3 done."


for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec1${i}.txt -d data4${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 100 --neurons 10 --quiet 1 >> vystup4${i}.txt
done
echo "test 4 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec2${i}.txt -d data5${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 200 --neurons 10 --quiet 1 >> vystup5${i}.txt
done
echo "test 5 done."

for i in $(seq 0 10)
do 
./main -n nejlepsi_jedinec3${i}.txt -d data6${i}.txt --NP 300 --F 0.7 --CR 0.3 --generations 300 --neurons 10 --quiet 1 >> vystup6${i}.txt
done
echo "test 6 done."

